FROM maven:3.8.5-openjdk-11 AS maven_build
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn package
EXPOSE 8080

# Run stage (slim image)
FROM openjdk:20-slim
WORKDIR /app
COPY /target/spring-boot-docker.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
